version: '3'

services:
  telegram-bot:
    build:
      context: ..  # Use parent directory as build context
      dockerfile: docker/app.Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../prompts:/app/prompts